### ISSUE TITLE
network-simple-0.4.3 fails to build with `network < 2.6.3.0`

### ISSUE THREAD

**Issue by sjakobi** [k0001/network-simple#36]
```
$ cabal install network-simple-0.4.3 --constraint 'network < 2.6.3'
<...>
src/Network/Simple/Internal.hs:58:24: error:
    Not in scope: ‘NS.tupleToHostAddress’
    Neither ‘Network.BSD’ nor ‘Network.Socket’ exports ‘tupleToHostAddress’.
   |
58 |   = NS.SockAddrInet p (NS.tupleToHostAddress
   |                        ^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build network-simple-0.4.3.
```

As a Hackage trustee, I have created a Hackage revision that should prevent users from encountering this error: https://hackage.haskell.org/package/network-simple-0.4.3/revisions/

**Comment by sjakobi** [comment]
I've made similar revisions for v0.4.1 and v0.4.2.
